const products = [
  {
    creatorId: 1,
    title: 'Small Plastic Sausages',
    description: 'Dicta et voluptate. Accusantium qui ut dolorem et maxime voluptates ipsam magni. Laudantium sequi doloribus nisi debitis ut accusantium sit itaque nobis. Quod aliquam atque in voluptas in eligendi voluptatum et at.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Shoes',
    numBackers: 16,
    goalDate: '6/13/2018',
    goalAmt: 47308,
    amtPledged: 13013,
    productId: 5
  },
  {
    creatorId: 2,
    title: 'Sleek Granite Chips',
    description: 'Voluptatem consectetur non eum non porro asperiores neque qui molestiae. Iusto harum sint atque sed ad aut voluptate. Et minima et qui id eveniet voluptates. Maiores aut incidunt. Molestiae ex aperiam laudantium debitis. Ut est voluptatem quasi porro.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 12,
    goalDate: '5/8/2018',
    goalAmt: 40823,
    amtPledged: 22123,
    productId: 4
  },
  {
    creatorId: 3,
    title: 'Small Rubber Salad',
    description: 'Animi odio autem vero qui deserunt eius. Officia repellendus doloribus magnam nisi quibusdam. Cumque dolor cupiditate rem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Clothing',
    numBackers: 12,
    goalDate: '9/21/2018',
    goalAmt: 15086,
    amtPledged: 7646,
    productId: 18
  },
  {
    creatorId: 4,
    title: 'Intelligent Plastic Cheese',
    description: 'Sit nostrum enim fugiat aut magni dolores. Quod dolor culpa ducimus officiis quia provident. Repellendus commodi minus quae debitis repellendus voluptatem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Outdoors',
    numBackers: 12,
    goalDate: '7/7/2018',
    goalAmt: 9345,
    amtPledged: 9231,
    productId: 24
  },
  {
    creatorId: 5,
    title: 'Tasty Steel Soap',
    description: 'Voluptatem quo ut et rerum ad quod qui reprehenderit velit. Eveniet et qui vero vero. Et ipsa ut enim. Fugiat blanditiis sed id id vero modi sit.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Books',
    numBackers: 10,
    goalDate: '6/28/2018',
    goalAmt: 11637,
    amtPledged: 2471,
    productId: 10
  },
  {
    creatorId: 6,
    title: 'Refined Metal Computer',
    description: 'Quo fuga ea. Dignissimos nihil atque. Non dignissimos et quae velit.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 10,
    goalDate: '5/17/2018',
    goalAmt: 49993,
    amtPledged: 36846,
    productId: 30
  },
  {
    creatorId: 7,
    title: 'Fantastic Rubber Gloves',
    description: 'Rerum nam rerum ex aliquid illo dolores. Sunt et in. Perspiciatis optio ut dolore repellendus eos quia temporibus. Voluptatibus fugit est. Maiores odit ut. Nisi harum et eveniet.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Books',
    numBackers: 7,
    goalDate: '6/2/2018',
    goalAmt: 13682,
    amtPledged: 10086,
    productId: 14
  },
  {
    creatorId: 8,
    title: 'Tasty Cotton Cheese',
    description: 'Debitis aut dolor. Hic dolorem maiores nihil temporibus ipsum. Earum deleniti suscipit fugiat voluptatem ut aut velit. Dolorem fugiat molestias commodi excepturi distinctio quod quia animi.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Baby',
    numBackers: 5,
    goalDate: '7/25/2018',
    goalAmt: 14487,
    amtPledged: 3704,
    productId: 16
  },
  {
    creatorId: 9,
    title: 'Incredible Steel Gloves',
    description: 'Eos maiores blanditiis odio. Nostrum magnam ut nam perferendis in necessitatibus. Inventore ea et sint ipsum. Dolore ut voluptas iure adipisci voluptatum natus exercitationem reprehenderit repellendus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Beauty',
    numBackers: 11,
    goalDate: '10/6/2018',
    goalAmt: 3604,
    amtPledged: 2933,
    productId: 54
  },
  {
    creatorId: 10,
    title: 'Rustic Plastic Ball',
    description: 'Ea aut placeat asperiores qui recusandae. Tempore voluptas nam mollitia at excepturi dolorum minus laboriosam nisi. Perspiciatis eum explicabo ut. Quaerat non blanditiis similique sequi. Cumque id amet aliquam excepturi deserunt rerum. Labore ut nobis tempore expedita eius impedit cumque maxime quis.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Automotive',
    numBackers: 9,
    goalDate: '10/12/2018',
    goalAmt: 45255,
    amtPledged: 40444,
    productId: 60
  },
  {
    creatorId: 11,
    title: 'Gorgeous Fresh Table',
    description: 'Aut iusto enim aperiam et distinctio quisquam nemo asperiores. Consequuntur est sunt omnis aut laborum quidem. In dolores sint et doloremque. Perspiciatis dolor beatae dolor non.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Grocery',
    numBackers: 7,
    goalDate: '10/28/2018',
    goalAmt: 28265,
    amtPledged: 18002,
    productId: 55
  },
  {
    creatorId: 12,
    title: 'Ergonomic Metal Table',
    description: 'Quidem est dolore vitae sapiente sit eos eveniet repudiandae. Molestias sed et consectetur deleniti. Qui sit tempore qui.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Automotive',
    numBackers: 2,
    goalDate: '5/24/2018',
    goalAmt: 49040,
    amtPledged: 24174,
    productId: 60
  },
  {
    creatorId: 13,
    title: 'Unbranded Frozen Car',
    description: 'Quae et architecto omnis magnam. Tempore harum est ipsa non praesentium. Fugit consequatur vero nostrum temporibus cumque recusandae sunt necessitatibus. Ut necessitatibus voluptates enim et aut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 13,
    goalDate: '12/27/2018',
    goalAmt: 42168,
    amtPledged: 29665,
    productId: 13
  },
  {
    creatorId: 14,
    title: 'Practical Metal Computer',
    description: 'Ut sed voluptatem sunt ducimus sit. Perspiciatis provident quia in. Aut eos eveniet incidunt soluta quis sunt. Est voluptatem et repellat maxime. Eum quas voluptas dolorem voluptatibus accusantium non omnis.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 3,
    goalDate: '9/5/2018',
    goalAmt: 28292,
    amtPledged: 8704,
    productId: 84
  },
  {
    creatorId: 15,
    title: 'Small Plastic Keyboard',
    description: 'Culpa consequatur quis. Mollitia voluptatem sit veritatis at earum nisi et nostrum. Ut magnam consequatur molestias itaque et commodi voluptas ut. Dolores sit consequatur quae aut. Est molestiae nihil dolorem sed aut dolor ut et est. Accusamus ab harum voluptatem consectetur consequatur reiciendis optio quia atque.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 9,
    goalDate: '7/8/2018',
    goalAmt: 18804,
    amtPledged: 6803,
    productId: 90
  },
  {
    creatorId: 16,
    title: 'Rustic Concrete Cheese',
    description: 'Repellat eligendi placeat quam maiores in. Tempore quia id. Quas quia occaecati dolores velit cum inventore. Autem ex autem voluptas voluptate dolorem accusamus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 19,
    goalDate: '10/20/2018',
    goalAmt: 13289,
    amtPledged: 7416,
    productId: 80
  },
  {
    creatorId: 17,
    title: 'Practical Fresh Shirt',
    description: 'Molestiae sapiente reiciendis eum ut sapiente. Eaque deserunt et reprehenderit sapiente eaque non placeat error. Perferendis beatae et debitis officia inventore sint eligendi ipsa et. Saepe et omnis eum quia quia officiis.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Baby',
    numBackers: 0,
    goalDate: '11/5/2018',
    goalAmt: 7280,
    amtPledged: 4351,
    productId: 85
  },
  {
    creatorId: 18,
    title: 'Licensed Frozen Chair',
    description: 'Autem eum ad dignissimos rerum rerum repellendus. Temporibus natus natus nam. Quia aut iure nostrum. Blanditiis aut quos omnis omnis. Quaerat atque est doloremque ea.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Grocery',
    numBackers: 3,
    goalDate: '9/26/2018',
    goalAmt: 48500,
    amtPledged: 47035,
    productId: 54
  },
  {
    creatorId: 19,
    title: 'Practical Rubber Computer',
    description: 'Omnis quas dolor delectus placeat eaque perspiciatis sint. Unde accusamus est atque pariatur tempore id eos placeat. Quaerat saepe est error perspiciatis harum ut placeat dolorem. Et magni qui. Voluptas repudiandae nobis temporibus possimus. Deserunt voluptatem ipsam qui velit sed voluptatem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Baby',
    numBackers: 18,
    goalDate: '5/7/2018',
    goalAmt: 47411,
    amtPledged: 42184,
    productId: 19
  },
  {
    creatorId: 20,
    title: 'Practical Soft Sausages',
    description: 'Et ea laborum et neque neque adipisci illo. Asperiores adipisci labore soluta maiores. Iure omnis officia dolorem. Sint non veniam eos sunt voluptas aperiam debitis autem. Autem est non.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 12,
    goalDate: '6/24/2018',
    goalAmt: 33234,
    amtPledged: 2728,
    productId: 40
  },
  {
    creatorId: 21,
    title: 'Generic Cotton Ball',
    description: 'Magni ut fuga dolorem odio dolor corrupti aut eius distinctio. Repellendus quae veniam cupiditate. Maiores ut facilis. Minus magnam iure.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 9,
    goalDate: '8/12/2018',
    goalAmt: 19825,
    amtPledged: 5506,
    productId: 21
  },
  {
    creatorId: 22,
    title: 'Rustic Soft Chicken',
    description: 'Aut cumque quo ad est nobis saepe aut. Laborum cumque dignissimos aliquid omnis autem delectus aspernatur dolorem. Magnam consequatur architecto quisquam animi aliquam. Corrupti atque libero fugiat.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Beauty',
    numBackers: 6,
    goalDate: '7/11/2018',
    goalAmt: 21023,
    amtPledged: 8846,
    productId: 132
  },
  {
    creatorId: 23,
    title: 'Awesome Granite Pizza',
    description: 'Eos consectetur magni. Aut beatae quo dolores laborum. Aut vitae labore. Eos qui labore assumenda. Quibusdam rem sint nam ea quae. Temporibus dolores voluptatem dignissimos est facilis.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 14,
    goalDate: '10/22/2018',
    goalAmt: 34921,
    amtPledged: 10345,
    productId: 69
  },
  {
    creatorId: 24,
    title: 'Tasty Wooden Ball',
    description: 'Tempore soluta perspiciatis minima rerum repellendus et. Iusto fugit facilis quibusdam quae quia est est commodi distinctio. Nihil beatae corporis qui cupiditate provident omnis commodi tempora. Praesentium omnis quaerat. Cumque vero consequatur id sequi impedit quos repellat.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Music',
    numBackers: 8,
    goalDate: '5/2/2018',
    goalAmt: 45623,
    amtPledged: 865,
    productId: 120
  },
  {
    creatorId: 25,
    title: 'Handmade Frozen Hat',
    description: 'Sit molestias totam repellat exercitationem cupiditate quos eveniet. Suscipit voluptatem dolorum nemo temporibus velit amet praesentium sint velit. Voluptas ipsum placeat quasi nostrum tempora laborum qui.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Music',
    numBackers: 0,
    goalDate: '9/23/2018',
    goalAmt: 27893,
    amtPledged: 6103,
    productId: 50
  },
  {
    creatorId: 26,
    title: 'Unbranded Cotton Bike',
    description: 'Voluptas tempora sit laboriosam. Neque et porro blanditiis eius explicabo odio. Est dignissimos et temporibus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 12,
    goalDate: '12/4/2018',
    goalAmt: 25610,
    amtPledged: 16578,
    productId: 26
  },
  {
    creatorId: 27,
    title: 'Intelligent Steel Cheese',
    description: 'Est sed provident libero enim. Vel deleniti distinctio praesentium. Harum autem labore aut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Health',
    numBackers: 15,
    goalDate: '9/8/2018',
    goalAmt: 29330,
    amtPledged: 338,
    productId: 135
  },
  {
    creatorId: 28,
    title: 'Sleek Concrete Table',
    description: 'Fuga maiores et quibusdam iusto earum ad nulla. Sed voluptatem ut sunt. Dicta fugit aperiam at est nam rerum. Eveniet beatae saepe iste eaque quae.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Books',
    numBackers: 6,
    goalDate: '11/6/2018',
    goalAmt: 25764,
    amtPledged: 1945,
    productId: 56
  },
  {
    creatorId: 29,
    title: 'Gorgeous Rubber Ball',
    description: 'Laboriosam aut corporis et fuga id. Sit beatae necessitatibus deserunt velit. Neque vero harum at. Qui quam tempora et vel eligendi est quae architecto ratione. Aut qui non eligendi voluptas odit culpa fuga natus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 13,
    goalDate: '12/16/2018',
    goalAmt: 16278,
    amtPledged: 3509,
    productId: 116
  },
  {
    creatorId: 30,
    title: 'Generic Steel Chips',
    description: 'Mollitia quia occaecati maiores dolore tempore omnis ut sint. Cumque doloribus sed dolorem tenetur neque consequatur maxime eos. Tempora voluptatibus beatae reiciendis laborum error occaecati aut voluptatibus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Tools',
    numBackers: 6,
    goalDate: '10/21/2018',
    goalAmt: 19719,
    amtPledged: 6533,
    productId: 150
  },
  {
    creatorId: 31,
    title: 'Tasty Concrete Towels',
    description: 'Et modi qui praesentium. Rerum quis ratione magni. Fuga perferendis culpa. Rerum inventore id. Et magni adipisci voluptatem accusamus soluta et.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Sports',
    numBackers: 7,
    goalDate: '12/6/2018',
    goalAmt: 7510,
    amtPledged: 493,
    productId: 217
  },
  {
    creatorId: 32,
    title: 'Fantastic Concrete Shirt',
    description: 'Illo sint ea eius veniam nisi cumque. Excepturi voluptate cupiditate at excepturi voluptates quo. Excepturi et aliquid. Sunt quas quaerat ut. Fuga dolor unde corrupti qui impedit enim. Quia aspernatur in sint ratione ut qui quia.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 13,
    goalDate: '8/15/2018',
    goalAmt: 13926,
    amtPledged: 13753,
    productId: 160
  },
  {
    creatorId: 33,
    title: 'Practical Steel Tuna',
    description: 'Eos aut autem sapiente molestias. Repellat atque adipisci minima suscipit porro ullam id. Quis rerum ducimus enim ut architecto omnis est. Ut fuga iure veniam qui harum ut sint. Unde delectus minima. Maiores dolorem delectus commodi ullam at.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 16,
    goalDate: '9/26/2018',
    goalAmt: 22030,
    amtPledged: 12171,
    productId: 198
  },
  {
    creatorId: 34,
    title: 'Small Cotton Shirt',
    description: 'Deleniti ea odio earum consequuntur. Officiis ut pariatur ab. Qui id eligendi voluptates est. Non veritatis cum autem dignissimos id eveniet est consequatur. Iusto ipsum quae. Suscipit numquam ipsam aliquam impedit et quidem minus soluta dignissimos.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 3,
    goalDate: '12/24/2018',
    goalAmt: 14398,
    amtPledged: 7621,
    productId: 102
  },
  {
    creatorId: 35,
    title: 'Gorgeous Fresh Cheese',
    description: 'Ullam est facilis rem nam dicta. Nemo impedit odit velit adipisci voluptatem veniam occaecati. Autem hic cum deleniti consectetur reprehenderit quas esse aliquam tempora.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 14,
    goalDate: '8/8/2018',
    goalAmt: 48355,
    amtPledged: 47424,
    productId: 210
  },
  {
    creatorId: 36,
    title: 'Unbranded Rubber Bacon',
    description: 'Quia rerum et officiis saepe. Deserunt doloribus laboriosam expedita beatae non vitae. Eum ut perspiciatis qui. Aspernatur laborum vitae dolores mollitia voluptatem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Clothing',
    numBackers: 5,
    goalDate: '8/9/2018',
    goalAmt: 24812,
    amtPledged: 23351,
    productId: 144
  },
  {
    creatorId: 37,
    title: 'Sleek Granite Fish',
    description: 'Labore dolores et sequi et voluptate non enim quia eum. Aut consequatur explicabo at fugiat odio iste nihil et laudantium. Dolorum nisi numquam nesciunt sed sit numquam quos sed voluptate. Exercitationem optio architecto esse dolor. Magnam facere voluptas labore cumque. Saepe vitae a in ipsum molestiae sit facilis dolor rerum.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 13,
    goalDate: '6/6/2018',
    goalAmt: 47792,
    amtPledged: 24924,
    productId: 111
  },
  {
    creatorId: 38,
    title: 'Incredible Steel Soap',
    description: 'Eveniet autem voluptatem et est. Quisquam recusandae et animi qui iure perferendis. Nemo autem architecto tempora corrupti perspiciatis iure.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Outdoors',
    numBackers: 1,
    goalDate: '7/16/2018',
    goalAmt: 10067,
    amtPledged: 9077,
    productId: 228
  },
  {
    creatorId: 39,
    title: 'Licensed Steel Pizza',
    description: 'Iure omnis qui omnis reprehenderit assumenda minus. Voluptatum vel repellat enim quo dolores eum aut doloremque beatae. Distinctio ut recusandae voluptate optio tempora qui pariatur placeat. Quos eos dolor dolor et accusantium debitis nihil similique laboriosam.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Kids',
    numBackers: 12,
    goalDate: '8/27/2018',
    goalAmt: 17748,
    amtPledged: 3816,
    productId: 39
  },
  {
    creatorId: 40,
    title: 'Incredible Granite Table',
    description: 'Voluptatem doloremque nisi tenetur odio. Possimus in officia voluptate ullam repellendus et. Dolor tempora excepturi porro est est qui vitae. Exercitationem commodi est doloribus aut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 2,
    goalDate: '9/15/2018',
    goalAmt: 3159,
    amtPledged: 1186,
    productId: 80
  },
  {
    creatorId: 41,
    title: 'Ergonomic Frozen Shirt',
    description: 'Pariatur assumenda sed. Qui eveniet quisquam voluptas sapiente beatae est eligendi soluta ad. Sed omnis asperiores provident qui maxime ea.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 16,
    goalDate: '10/26/2018',
    goalAmt: 35995,
    amtPledged: 735,
    productId: 287
  },
  {
    creatorId: 42,
    title: 'Intelligent Concrete Towels',
    description: 'Dolore nulla dicta impedit reprehenderit nihil eos aut nihil. Et est quaerat ea eum. Harum et voluptatem qui nulla a aut magnam. Eum placeat quia aliquid est. Mollitia architecto praesentium dolore corporis dolores ea. Voluptate dolore tempore rem in esse atque velit ex.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Shoes',
    numBackers: 13,
    goalDate: '11/17/2018',
    goalAmt: 36641,
    amtPledged: 16672,
    productId: 294
  },
  {
    creatorId: 43,
    title: 'Unbranded Soft Mouse',
    description: 'Id tempora debitis sint est dolorem qui. Sit rerum dolorem molestiae id assumenda enim et illo. Ut sequi sapiente saepe hic. Numquam velit error similique accusantium quos non ut error.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 15,
    goalDate: '5/1/2018',
    goalAmt: 18039,
    amtPledged: 12310,
    productId: 301
  },
  {
    creatorId: 44,
    title: 'Unbranded Fresh Soap',
    description: 'Vitae sed dolor quisquam. Dicta maiores aut ipsam possimus. Sit neque modi sunt illo consequatur. Et facilis fugiat aut aspernatur sed occaecati.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Tools',
    numBackers: 13,
    goalDate: '11/26/2018',
    goalAmt: 34564,
    amtPledged: 711,
    productId: 176
  },
  {
    creatorId: 45,
    title: 'Refined Wooden Car',
    description: 'Aspernatur est reiciendis pariatur ipsum quidem numquam fugiat omnis nesciunt. Eos possimus debitis labore. Quae recusandae modi omnis omnis omnis.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Sports',
    numBackers: 10,
    goalDate: '12/27/2018',
    goalAmt: 10480,
    amtPledged: 3804,
    productId: 90
  },
  {
    creatorId: 46,
    title: 'Licensed Frozen Keyboard',
    description: 'Laborum officia quas totam cupiditate sunt esse quod. Et eius debitis qui est sint aliquam sapiente. Distinctio alias suscipit culpa tempora aut esse ea numquam. Et consequatur qui esse quia molestias nesciunt sed.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Baby',
    numBackers: 16,
    goalDate: '10/25/2018',
    goalAmt: 9725,
    amtPledged: 5347,
    productId: 184
  },
  {
    creatorId: 47,
    title: 'Handmade Soft Chicken',
    description: 'Quasi dolorem ea iste. Minus dolor libero perferendis aut. Quae consequatur cupiditate. Veritatis consequatur aut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 7,
    goalDate: '12/2/2018',
    goalAmt: 47813,
    amtPledged: 10735,
    productId: 94
  },
  {
    creatorId: 48,
    title: 'Small Fresh Mouse',
    description: 'Aliquam et aliquam. Et explicabo error facere. Aspernatur at aut eveniet omnis reprehenderit a nemo occaecati.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 20,
    goalDate: '9/26/2018',
    goalAmt: 4795,
    amtPledged: 3177,
    productId: 96
  },
  {
    creatorId: 49,
    title: 'Awesome Steel Pizza',
    description: 'Non itaque in quod aut. Neque nostrum veritatis sint magnam quia. Eligendi pariatur aut et minus odio optio. Debitis nostrum et excepturi.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Tools',
    numBackers: 18,
    goalDate: '10/9/2018',
    goalAmt: 22374,
    amtPledged: 2377,
    productId: 294
  },
  {
    creatorId: 50,
    title: 'Rustic Steel Soap',
    description: 'Voluptas fugit sit et quia nulla laborum. Voluptatibus nihil facere debitis delectus cupiditate repellendus minima id. Amet fugit ea distinctio harum omnis nostrum harum molestias. Earum voluptas cum voluptatem aspernatur beatae. Id rerum exercitationem est distinctio tenetur consectetur tenetur autem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 20,
    goalDate: '11/23/2018',
    goalAmt: 17530,
    amtPledged: 3469,
    productId: 200
  },
  {
    creatorId: 51,
    title: 'Unbranded Soft Tuna',
    description: 'Eos id at maiores repellendus consequuntur eveniet labore facere. Illo quia rerum est non et reiciendis velit quos exercitationem. Itaque consequuntur est et.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Beauty',
    numBackers: 3,
    goalDate: '10/19/2018',
    goalAmt: 40537,
    amtPledged: 37454,
    productId: 51
  },
  {
    creatorId: 52,
    title: 'Incredible Cotton Ball',
    description: 'Dolorum officia praesentium expedita. Quas unde expedita ullam cum quae. Veritatis aut aliquam excepturi blanditiis impedit corporis laudantium quia. Minus provident et maiores. Sint voluptatem nulla vitae libero impedit esse quia. Saepe praesentium aliquid est voluptatem vel.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Books',
    numBackers: 17,
    goalDate: '11/26/2018',
    goalAmt: 10692,
    amtPledged: 9770,
    productId: 260
  },
  {
    creatorId: 53,
    title: 'Handmade Plastic Mouse',
    description: 'Nemo ipsam consectetur rerum doloremque laudantium at autem est et. Ducimus dolorem sapiente molestiae sint sed est sint. Hic voluptatum molestias qui inventore modi. Ut minus illo molestiae dignissimos.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 10,
    goalDate: '12/10/2018',
    goalAmt: 18386,
    amtPledged: 8252,
    productId: 53
  },
  {
    creatorId: 54,
    title: 'Fantastic Cotton Cheese',
    description: 'Est ea magnam voluptatem eligendi. Facilis dignissimos id unde. Et enim repellendus beatae consequatur ab. Consequatur error delectus esse quae. Ullam saepe nihil quae magni culpa et culpa dicta. Reiciendis perferendis eaque.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Music',
    numBackers: 10,
    goalDate: '6/1/2018',
    goalAmt: 9456,
    amtPledged: 831,
    productId: 162
  },
  {
    creatorId: 55,
    title: 'Refined Frozen Keyboard',
    description: 'Et voluptatem facilis sapiente qui quod. Neque aut dignissimos saepe soluta qui qui at ex dolorem. Id facere laboriosam id animi non recusandae ut esse. Possimus aspernatur aut esse. Hic porro fugiat ipsam molestiae possimus veritatis aut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 1,
    goalDate: '12/24/2018',
    goalAmt: 5695,
    amtPledged: 1710,
    productId: 55
  },
  {
    creatorId: 56,
    title: 'Unbranded Rubber Gloves',
    description: 'Possimus voluptatem eligendi eius. Iusto ut est. Rerum aut quia qui. Sed itaque et dignissimos quia ut corrupti nihil sit.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 3,
    goalDate: '10/26/2018',
    goalAmt: 18300,
    amtPledged: 13885,
    productId: 280
  },
  {
    creatorId: 57,
    title: 'Practical Soft Keyboard',
    description: 'Est voluptatum fugiat rerum porro omnis et vitae neque sed. Minus sit eum facere vero repellat quis qui reiciendis ut. Est qui in omnis unde. Illo sunt sint inventore. Aut id placeat impedit qui repellendus. Voluptatem occaecati distinctio ut et aut iusto quas beatae tempore.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 18,
    goalDate: '9/20/2018',
    goalAmt: 28020,
    amtPledged: 5107,
    productId: 57
  },
  {
    creatorId: 58,
    title: 'Gorgeous Steel Tuna',
    description: 'Voluptatem nemo amet. Soluta non sint labore iste. Aut et architecto nemo hic voluptate saepe nihil. Libero blanditiis odit nisi esse dolorem cupiditate recusandae aspernatur.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Automotive',
    numBackers: 4,
    goalDate: '12/25/2018',
    goalAmt: 23149,
    amtPledged: 4266,
    productId: 348
  },
  {
    creatorId: 59,
    title: 'Small Plastic Chair',
    description: 'Hic totam labore. Et ipsa ut porro minima. Quasi cupiditate quam aut quia magnam asperiores suscipit adipisci enim. Vitae aut illum odio.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Kids',
    numBackers: 16,
    goalDate: '10/14/2018',
    goalAmt: 39084,
    amtPledged: 6700,
    productId: 59
  },
  {
    creatorId: 60,
    title: 'Rustic Cotton Sausages',
    description: 'Molestiae aperiam dicta dicta iste quam. Aliquam dolores repellat eos impedit voluptas. Beatae dolorem debitis natus laborum minus nemo. Accusamus magnam ut veniam ut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 2,
    goalDate: '12/26/2018',
    goalAmt: 27646,
    amtPledged: 4197,
    productId: 240
  },
  {
    creatorId: 61,
    title: 'Handcrafted Metal Bacon',
    description: 'Et quod reiciendis ut eligendi rerum atque. Soluta nobis eveniet ea voluptatibus cumque laborum reprehenderit ratione aut. Vitae enim nihil quo.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 18,
    goalDate: '12/20/2018',
    goalAmt: 16816,
    amtPledged: 6247,
    productId: 366
  },
  {
    creatorId: 62,
    title: 'Awesome Rubber Keyboard',
    description: 'Numquam ab debitis quisquam soluta minima numquam. Aut quaerat occaecati. Sunt et excepturi velit doloribus itaque sint.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 5,
    goalDate: '11/12/2018',
    goalAmt: 25839,
    amtPledged: 197,
    productId: 310
  },
  {
    creatorId: 63,
    title: 'Unbranded Steel Pizza',
    description: 'Reiciendis laudantium voluptatum nesciunt. Soluta dolorem hic consequatur eos iure rem. Quia qui fugiat eaque blanditiis quasi. Id ipsum harum voluptatem. Possimus modi culpa molestias et voluptatem reiciendis unde.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Beauty',
    numBackers: 1,
    goalDate: '12/6/2018',
    goalAmt: 30298,
    amtPledged: 22585,
    productId: 315
  },
  {
    creatorId: 64,
    title: 'Practical Steel Computer',
    description: 'Molestiae explicabo illum rerum qui. Possimus sed voluptatem quis quidem nulla. Aut odit autem qui vel. Non vel quos et voluptates ab occaecati. Nihil est ea culpa sed reiciendis illo.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Tools',
    numBackers: 8,
    goalDate: '6/18/2018',
    goalAmt: 43988,
    amtPledged: 39316,
    productId: 384
  },
  {
    creatorId: 65,
    title: 'Intelligent Frozen Chicken',
    description: 'Occaecati ab molestiae illum fugit unde. Ab ut et non quos. Eveniet odit quo esse. Voluptatem iure nostrum maxime ex itaque placeat sapiente. Enim iusto modi asperiores pariatur aut animi reiciendis natus sint.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Outdoors',
    numBackers: 6,
    goalDate: '11/5/2018',
    goalAmt: 4872,
    amtPledged: 3407,
    productId: 390
  },
  {
    creatorId: 66,
    title: 'Awesome Plastic Computer',
    description: 'Quod ratione rerum et corporis minus praesentium tempora sed reiciendis. Aut enim optio hic aut perspiciatis saepe autem. Architecto maiores esse hic quos fuga sunt libero tenetur. Impedit sunt nam consequatur. Quas hic dicta voluptatem saepe nostrum officiis sint.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Books',
    numBackers: 8,
    goalDate: '6/8/2018',
    goalAmt: 27347,
    amtPledged: 7547,
    productId: 66
  },
  {
    creatorId: 67,
    title: 'Generic Steel Chair',
    description: 'Velit dicta similique laborum inventore. Impedit vel et. Autem qui voluptatem quas repellendus ipsa. Maiores minima debitis ad at laboriosam. Unde dolore vero praesentium quibusdam ex deserunt eius. Tempore quam harum cupiditate facere nostrum nisi nam dolorum.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 1,
    goalDate: '12/20/2018',
    goalAmt: 33413,
    amtPledged: 27115,
    productId: 402
  },
  {
    creatorId: 68,
    title: 'Ergonomic Steel Shoes',
    description: 'Doloremque eum ut quia. Doloribus qui et qui est. Qui rerum et aut ducimus recusandae fugiat sunt itaque voluptatem. Sapiente id recusandae nihil temporibus repudiandae laborum ipsum non natus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Kids',
    numBackers: 14,
    goalDate: '8/6/2018',
    goalAmt: 37379,
    amtPledged: 23769,
    productId: 136
  },
  {
    creatorId: 69,
    title: 'Small Cotton Computer',
    description: 'Rerum eos ut est soluta nam et consequatur eaque molestias. Saepe est hic aut qui vero. Ut nemo illum consectetur veritatis nemo aut qui.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 6,
    goalDate: '7/18/2018',
    goalAmt: 9117,
    amtPledged: 4381,
    productId: 276
  },
  {
    creatorId: 70,
    title: 'Awesome Frozen Hat',
    description: 'Sequi totam nihil molestias cum aut inventore suscipit id commodi. Consequatur tempora atque et tempore dolorum. Aut quasi odit in sit. Dolorem unde qui. Et dolor voluptatem. Assumenda fuga suscipit sed placeat sint voluptate.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 8,
    goalDate: '10/10/2018',
    goalAmt: 12870,
    amtPledged: 12616,
    productId: 420
  },
  {
    creatorId: 71,
    title: 'Intelligent Fresh Gloves',
    description: 'Qui nihil voluptatibus libero. Magnam aliquid sint qui doloribus. Natus enim earum expedita dignissimos velit quas. Dolore aut ut. Perspiciatis ex qui veritatis quas. Quaerat quibusdam sint illo.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Computers',
    numBackers: 2,
    goalDate: '5/17/2018',
    goalAmt: 38809,
    amtPledged: 15178,
    productId: 426
  },
  {
    creatorId: 72,
    title: 'Awesome Plastic Fish',
    description: 'Qui et vel omnis et voluptatibus impedit id et ex. Praesentium in repellendus dolorem voluptas impedit nam mollitia. Incidunt omnis quod eum fugiat qui pariatur commodi repellat. Vel molestiae dolore porro nam facere sed. Praesentium earum et commodi modi.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Shoes',
    numBackers: 1,
    goalDate: '7/24/2018',
    goalAmt: 15981,
    amtPledged: 14378,
    productId: 216
  },
  {
    creatorId: 73,
    title: 'Handcrafted Frozen Tuna',
    description: 'Omnis aliquid provident et omnis consequatur quae sed. Beatae sit voluptas rem rerum vel voluptates. Rerum est nulla ex sed impedit dolor quis sequi.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 19,
    goalDate: '8/24/2018',
    goalAmt: 1852,
    amtPledged: 420,
    productId: 146
  },
  {
    creatorId: 74,
    title: 'Incredible Plastic Shirt',
    description: 'Dolores qui ab nemo voluptatem sunt maiores voluptatum. Maiores ullam et ea sint. Soluta fuga est deleniti velit qui. Id quia placeat quod magnam sit ad.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Toys',
    numBackers: 16,
    goalDate: '8/21/2018',
    goalAmt: 10735,
    amtPledged: 8129,
    productId: 370
  },
  {
    creatorId: 75,
    title: 'Unbranded Steel Table',
    description: 'Possimus tempora beatae est ut. Ut similique quibusdam perspiciatis ea iusto provident. Sequi sint ut earum. Dolore sit cumque officiis molestiae doloribus et.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Baby',
    numBackers: 4,
    goalDate: '12/2/2018',
    goalAmt: 14004,
    amtPledged: 5598,
    productId: 75
  },
  {
    creatorId: 76,
    title: 'Small Cotton Mouse',
    description: 'Qui doloribus sunt minima ipsa voluptate unde. Nam eligendi minus architecto. Laudantium ab quia molestiae ut illum. Numquam voluptatibus consequatur et maiores quia.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 19,
    goalDate: '8/16/2018',
    goalAmt: 9497,
    amtPledged: 1804,
    productId: 228
  },
  {
    creatorId: 77,
    title: 'Tasty Fresh Tuna',
    description: 'Et id voluptatibus occaecati quo omnis. Et necessitatibus culpa. Placeat quia id aut et iure optio maxime.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Sports',
    numBackers: 9,
    goalDate: '6/28/2018',
    goalAmt: 3167,
    amtPledged: 2408,
    productId: 77
  },
  {
    creatorId: 78,
    title: 'Licensed Concrete Bike',
    description: 'Doloribus voluptatem doloremque sed magni. Est corporis vel in dolor ratione. Qui illo inventore sit ullam labore. Enim provident vitae expedita placeat sit culpa earum. Sapiente aperiam sit magni et sunt fugit neque. Vitae commodi aut nobis et aut doloremque aut exercitationem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Shoes',
    numBackers: 4,
    goalDate: '6/18/2018',
    goalAmt: 2453,
    amtPledged: 676,
    productId: 156
  },
  {
    creatorId: 79,
    title: 'Rustic Wooden Cheese',
    description: 'Delectus ipsam quidem nesciunt ducimus numquam. Perferendis sit itaque aspernatur est similique eligendi. Sunt aperiam soluta ea ipsum sit. Id aut voluptate qui inventore distinctio. Aut aut enim atque tempora quis. Voluptatem hic tempore earum qui minima praesentium atque reiciendis.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 3,
    goalDate: '8/26/2018',
    goalAmt: 17376,
    amtPledged: 4707,
    productId: 474
  },
  {
    creatorId: 80,
    title: 'Incredible Concrete Bike',
    description: 'Provident recusandae fugit velit quia natus. Eius enim ut. Esse modi vero fugit voluptas consequuntur. Qui accusantium omnis. Cum accusantium est voluptatem.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Baby',
    numBackers: 8,
    goalDate: '6/19/2018',
    goalAmt: 40277,
    amtPledged: 12576,
    productId: 480
  },
  {
    creatorId: 81,
    title: 'Rustic Granite Salad',
    description: 'Ut saepe harum quia aut et veritatis corrupti ipsum. Sunt est qui magni est eos voluptatibus corporis. Quaerat eos sed in eveniet aut laboriosam qui.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 13,
    goalDate: '11/20/2018',
    goalAmt: 21899,
    amtPledged: 15761,
    productId: 405
  },
  {
    creatorId: 82,
    title: 'Gorgeous Plastic Computer',
    description: 'Blanditiis consectetur voluptates aut labore ab recusandae. Aut sit est quis quia voluptatem esse. Cupiditate omnis nisi iste nulla aut.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Beauty',
    numBackers: 18,
    goalDate: '9/21/2018',
    goalAmt: 33695,
    amtPledged: 19999,
    productId: 164
  },
  {
    creatorId: 83,
    title: 'Sleek Metal Pants',
    description: 'Qui nostrum id nisi quis. Fugit et sequi rerum in officiis quasi doloribus recusandae. Voluptatem quis aut. Consequatur sunt ipsa error fuga molestiae debitis numquam eius consequuntur. Impedit dolores esse repudiandae consequatur consectetur harum perferendis voluptatem. Voluptates omnis illo maxime delectus natus vero animi nemo.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Health',
    numBackers: 3,
    goalDate: '5/27/2018',
    goalAmt: 47349,
    amtPledged: 9794,
    productId: 415
  },
  {
    creatorId: 84,
    title: 'Handmade Wooden Chair',
    description: 'Voluptas eligendi voluptatem. Ipsa tenetur at quia. Laudantium sint adipisci enim. Sed omnis in nihil itaque quo. Eum a ab consequuntur amet suscipit nobis voluptatibus ut sit. Est ipsa numquam laboriosam tempore repellat qui qui.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Clothing',
    numBackers: 14,
    goalDate: '12/25/2018',
    goalAmt: 29884,
    amtPledged: 18172,
    productId: 420
  },
  {
    creatorId: 85,
    title: 'Gorgeous Plastic Shoes',
    description: 'Et qui possimus et voluptate. Saepe quo qui. Culpa qui eos est nulla est consequatur quidem ipsum dolorum.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Clothing',
    numBackers: 3,
    goalDate: '11/3/2018',
    goalAmt: 29340,
    amtPledged: 8957,
    productId: 85
  },
  {
    creatorId: 86,
    title: 'Handmade Granite Keyboard',
    description: 'Et aut dolor deserunt velit eaque ut. Occaecati et ullam voluptas et beatae. Et nobis quas et perferendis sed. Minima ut voluptas adipisci laudantium beatae.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Movies',
    numBackers: 4,
    goalDate: '10/16/2018',
    goalAmt: 34816,
    amtPledged: 31465,
    productId: 258
  },
  {
    creatorId: 87,
    title: 'Sleek Frozen Mouse',
    description: 'Quia aspernatur commodi quo atque ut. Consequatur dolor tempora minus. Corrupti impedit esse aspernatur quia. Velit possimus quia numquam unde aperiam occaecati. Dolor nulla dolores est sit optio natus molestiae quidem facere. Ut sequi sed voluptatem eum consequatur cumque delectus numquam facere.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 16,
    goalDate: '5/5/2018',
    goalAmt: 34799,
    amtPledged: 1328,
    productId: 261
  },
  {
    creatorId: 88,
    title: 'Intelligent Granite Salad',
    description: 'Odio nihil odit distinctio doloribus et fuga. Natus amet sed eius nisi nobis. Dolorum dignissimos corrupti amet quibusdam voluptates. Corrupti fuga deleniti itaque sunt nulla.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Clothing',
    numBackers: 2,
    goalDate: '6/28/2018',
    goalAmt: 9587,
    amtPledged: 3935,
    productId: 88
  },
  {
    creatorId: 89,
    title: 'Refined Soft Pizza',
    description: 'Enim corrupti nihil repellendus et labore quis. Qui delectus nisi temporibus at officia eos adipisci tempore. Facilis tenetur et et sint.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 19,
    goalDate: '12/5/2018',
    goalAmt: 31271,
    amtPledged: 10109,
    productId: 178
  },
  {
    creatorId: 90,
    title: 'Small Granite Tuna',
    description: 'Ipsam quod consectetur. Cum ut eligendi sed commodi. Numquam non cupiditate voluptatem error iusto non qui nobis modi. Quisquam deleniti non nulla. Numquam magni at.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Electronics',
    numBackers: 8,
    goalDate: '6/1/2018',
    goalAmt: 9170,
    amtPledged: 8665,
    productId: 90
  },
  {
    creatorId: 91,
    title: 'Tasty Cotton Shirt',
    description: 'Quaerat sed possimus iusto consequatur in enim error. Reprehenderit illum et qui qui. Ipsam a velit et porro molestias sunt et. Sit pariatur et voluptatum ad quibusdam omnis sed autem sit. Unde voluptas doloremque. Aspernatur ut sint.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Grocery',
    numBackers: 17,
    goalDate: '12/12/2018',
    goalAmt: 1758,
    amtPledged: 1085,
    productId: 91
  },
  {
    creatorId: 92,
    title: 'Awesome Concrete Gloves',
    description: 'Est aliquid optio reiciendis. Molestias deleniti perferendis distinctio consequatur qui. Neque voluptatem ullam veritatis iure odio. Eveniet est neque aut quis. Enim occaecati fugiat nobis dolore sit quia.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Automotive',
    numBackers: 20,
    goalDate: '12/27/2018',
    goalAmt: 19170,
    amtPledged: 3520,
    productId: 460
  },
  {
    creatorId: 93,
    title: 'Small Granite Ball',
    description: 'Ullam et sit distinctio quo. In totam qui ut totam praesentium. Quia praesentium voluptas eos deserunt repellat error enim. Animi occaecati qui sed eius ex nam voluptatem. Minus similique voluptas nihil maxime. Veritatis ea ea voluptates voluptate delectus.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Shoes',
    numBackers: 16,
    goalDate: '11/1/2018',
    goalAmt: 33862,
    amtPledged: 18624,
    productId: 372
  },
  {
    creatorId: 94,
    title: 'Awesome Steel Pizza',
    description: 'Veniam reprehenderit nobis sunt. Tempore nulla eum. Fugit pariatur sit nihil exercitationem minus repudiandae. Quibusdam laborum ipsum minima aliquam provident porro qui et.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Industrial',
    numBackers: 9,
    goalDate: '8/15/2018',
    goalAmt: 30252,
    amtPledged: 3418,
    productId: 282
  },
  {
    creatorId: 95,
    title: 'Fantastic Fresh Fish',
    description: 'Quas non tempore nulla ex porro. Incidunt quia eligendi quae et qui cum pariatur. Eos deleniti non est et omnis suscipit. Recusandae et numquam nulla. Enim error saepe. Nihil ut repudiandae et sit cumque laborum quisquam recusandae sequi.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Garden',
    numBackers: 2,
    goalDate: '11/26/2018',
    goalAmt: 46790,
    amtPledged: 38518,
    productId: 380
  },
  {
    creatorId: 96,
    title: 'Ergonomic Metal Sausages',
    description: 'Asperiores aut perferendis dolor reiciendis et aut. Voluptatem et eos sint placeat voluptatem quam. Officia nobis sunt impedit et. Provident molestiae et dolorum.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Sports',
    numBackers: 4,
    goalDate: '12/12/2018',
    goalAmt: 33121,
    amtPledged: 18259,
    productId: 576
  },
  {
    creatorId: 97,
    title: 'Licensed Granite Chicken',
    description: 'Aliquam eveniet autem sunt magnam quae cumque. Minima perferendis ipsam aut adipisci. In dolores vel deleniti optio molestiae. Adipisci quis mollitia eaque itaque ad ratione ut veritatis. Ab quasi sit. Ea harum cumque.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Jewelery',
    numBackers: 4,
    goalDate: '6/20/2018',
    goalAmt: 47448,
    amtPledged: 43134,
    productId: 291
  },
  {
    creatorId: 98,
    title: 'Refined Plastic Shirt',
    description: 'Commodi aut optio itaque itaque est voluptas placeat error. Fugit quibusdam autem id modi reiciendis quasi sit cupiditate. Labore labore cupiditate autem. Sit qui occaecati. Nisi consequatur consequatur cum itaque id quo perspiciatis fugit hic.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Automotive',
    numBackers: 1,
    goalDate: '8/7/2018',
    goalAmt: 29676,
    amtPledged: 19783,
    productId: 294
  },
  {
    creatorId: 99,
    title: 'Incredible Concrete Pizza',
    description: 'Rem quibusdam quia omnis expedita ullam in sunt rerum. Quod sunt voluptatibus voluptas harum et quasi officiis sed quos. Dolores necessitatibus odit tenetur asperiores commodi provident ut. Eveniet commodi et autem voluptatum voluptatem sit. Quia tenetur tempore.',
    mainImg: 'http://lorempixel.com/640/480/business',
    category: 'Games',
    numBackers: 4,
    goalDate: '7/19/2018',
    goalAmt: 18865,
    amtPledged: 3902,
    productId: 297
  }
]
